# Generated by Django 3.2.7 on 2021-09-10 09:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('index', '0003_portfolio'),
    ]

    operations = [
        migrations.CreateModel(
            name='bestseller',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mainimage1', models.ImageField(upload_to='Product')),
                ('mainimage2', models.ImageField(upload_to='Product')),
                ('mainimage3', models.ImageField(upload_to='Product')),
                ('mainimage4', models.ImageField(upload_to='Product')),
                ('mainimage5', models.ImageField(upload_to='Product')),
                ('name', models.CharField(max_length=264)),
                ('preview_text', models.TextField(max_length=200, verbose_name='Preview Text')),
                ('details_text', models.TextField(max_length=5000, verbose_name='Description')),
                ('price', models.FloatField()),
                ('created', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['created'],
            },
        ),
    ]
