# Generated by Django 3.2.7 on 2021-09-16 16:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('index', '0004_bestseller'),
    ]

    operations = [
        migrations.DeleteModel(
            name='bestseller',
        ),
    ]
